"""Add appauto_branch field to TaskRecord

Revision ID: 5b58aff1ebc9
Revises: 3123e7766f8a
Create Date: 2025-12-09 16:17:07.931534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b58aff1ebc9'
down_revision: Union[str, Sequence[str], None] = '3123e7766f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskrecord', sa.Column('appauto_branch', sa.String(), nullable=True))
    op.create_index(op.f('ix_taskrecord_appauto_branch'), 'taskrecord', ['appauto_branch'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskrecord_appauto_branch'), table_name='taskrecord')
    op.drop_column('taskrecord', 'appauto_branch')
    # ### end Alembic commands ###
